before_all do
  setup_circle_ci
end

lane :publish_to_firebase do |options|
  commit = last_git_commit
  build_notes = "Notes: #{commit[:message]}. Built by #{commit[:author]}"

  # sign_apk_lane(flavor: options[:flavor].capitalize, type: release_type)
  # Upload build to Firebase
  firebase_app_distribution(
    app: "#{options[:app_id]}",
    groups: "name-of-your-test-group",
    release_notes: build_notes,
    apk_path: "app/build/outputs/apk/release/app-release.apk",
    firebase_cli_token: "#{options[:firebase_token]}"
  )
end
